name: Poetry con Script Oficial

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python 🐍
        # Este paso es esencial para que 'python3' esté disponible.
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Poetry con el Script Oficial 📦
        # Ejecuta el script de instalación en el runner.
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Instalar dependencias con Poetry
        # Asegúrate de que el PATH esté actualizado para usar 'poetry'
        # o puedes necesitar usar el path completo si la instalación es local.
        # Por lo general, en los runners de GitHub, el comando 'poetry' estará disponible.
        run: poetry install --no-interaction --no-root

      - name: Ejecutar el script
        run: poetry run python partidos_quiniela/partidos.py