name: Python & Poetry Simplificado

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python y Poetry (incluye cache) 游닍
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Versi칩n de Python
          # Al usar cache: 'poetry', la acci칩n:
          # 1. Instala Poetry
          # 2. Configura el cache usando poetry.lock
          cache: 'poetry'

      - name: Instalar dependencias
        # Poetry ya est치 instalado y el cache est치 configurado,
        # por lo que este paso ser치 r치pido si no hay cambios en poetry.lock.
        run: poetry install --no-interaction --no-root

      - name: Ejecutar el script
        # Ejecuta el script dentro del entorno virtual de Poetry.
        run: poetry run python partidos_quiniela/partidos.py